"use client";

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useTier } from '@/contexts/TierContext';

interface WhiteLabelConfig {
  logo: string; // base64 or URL
  companyName: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headerText: string;
  footerText: string;
  showTripCostInsightsBranding: boolean;
}

const DEFAULT_CONFIG: WhiteLabelConfig = {
  logo: '',
  companyName: 'VoyagrIQ',
  primaryColor: '#2563eb',
  secondaryColor: '#7c3aed',
  accentColor: '#ec4899',
  headerText: 'Travel Analytics Report',
  footerText: 'Generated by VoyagrIQ',
  showTripCostInsightsBranding: true,
};

const COLOR_PRESETS = {
  default: {
    name: 'Default Blue',
    primaryColor: '#2563eb',
    secondaryColor: '#7c3aed',
    accentColor: '#ec4899',
  },
  corporate: {
    name: 'Corporate Blue',
    primaryColor: '#1e40af',
    secondaryColor: '#0369a1',
    accentColor: '#0891b2',
  },
  modern: {
    name: 'Modern Purple',
    primaryColor: '#7c3aed',
    secondaryColor: '#a855f7',
    accentColor: '#ec4899',
  },
  professional: {
    name: 'Professional Green',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    accentColor: '#14b8a6',
  },
  bold: {
    name: 'Bold Red',
    primaryColor: '#dc2626',
    secondaryColor: '#ea580c',
    accentColor: '#f59e0b',
  },
  elegant: {
    name: 'Elegant Navy',
    primaryColor: '#1e3a8a',
    secondaryColor: '#4338ca',
    accentColor: '#6366f1',
  },
  warm: {
    name: 'Warm Orange',
    primaryColor: '#ea580c',
    secondaryColor: '#f59e0b',
    accentColor: '#fbbf24',
  },
};

const STORAGE_KEY = 'voyagriq-white-label';

export default function WhiteLabelSettings() {
  const { currentTier, isSignedIn } = useTier();
  const router = useRouter();
  const [config, setConfig] = useState<WhiteLabelConfig>(DEFAULT_CONFIG);
  const [logoPreview, setLogoPreview] = useState<string>('');
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    if (!isSignedIn) {
      router.push('/login');
      return;
    }

    if (currentTier !== 'premium') {
      router.push('/subscription');
      return;
    }

    // Load saved config
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        setConfig(parsed);
        setLogoPreview(parsed.logo);
      } catch (e) {
        console.error('Error loading white-label config:', e);
      }
    }
  }, [isSignedIn, currentTier, router]);

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      alert('Please upload an image file');
      return;
    }

    // Validate file size (max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      alert('Logo must be less than 2MB');
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      const base64 = reader.result as string;
      setLogoPreview(base64);
      setConfig({ ...config, logo: base64 });
    };
    reader.readAsDataURL(file);
  };

  const handleSave = () => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  const handleReset = () => {
    if (confirm('Are you sure you want to reset to default settings?')) {
      setConfig(DEFAULT_CONFIG);
      setLogoPreview('');
      localStorage.removeItem(STORAGE_KEY);
    }
  };

  const handleApplyPreset = (presetKey: keyof typeof COLOR_PRESETS) => {
    const preset = COLOR_PRESETS[presetKey];
    setConfig({
      ...config,
      primaryColor: preset.primaryColor,
      secondaryColor: preset.secondaryColor,
      accentColor: preset.accentColor,
    });
  };

  if (currentTier !== 'premium') {
    return null;
  }

  return (
    <div className="max-w-7xl mx-auto p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">White-Label Settings</h1>
        <p className="text-gray-600">
          Customize your reports with your own branding (Premium feature)
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Settings Form */}
        <div className="space-y-6">
          {/* Logo Upload */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Company Logo</h2>
            <div className="space-y-4">
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                {logoPreview ? (
                  <div className="space-y-4">
                    <img
                      src={logoPreview}
                      alt="Logo preview"
                      className="max-h-32 mx-auto"
                    />
                    <button
                      onClick={() => {
                        setLogoPreview('');
                        setConfig({ ...config, logo: '' });
                      }}
                      className="text-red-600 hover:text-red-700 text-sm cursor-pointer"
                    >
                      Remove Logo
                    </button>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <svg
                      className="mx-auto h-12 w-12 text-gray-400"
                      stroke="currentColor"
                      fill="none"
                      viewBox="0 0 48 48"
                    >
                      <path
                        d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02"
                        strokeWidth={2}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                    <div className="text-sm text-gray-600">
                      <label
                        htmlFor="logo-upload"
                        className="cursor-pointer text-blue-600 hover:text-blue-700 font-semibold"
                      >
                        Upload a logo
                      </label>
                      <input
                        id="logo-upload"
                        type="file"
                        accept="image/*"
                        onChange={handleLogoUpload}
                        className="hidden"
                      />
                    </div>
                    <p className="text-xs text-gray-500">PNG, JPG up to 2MB</p>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Company Name */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Company Information</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Company Name
                </label>
                <input
                  type="text"
                  value={config.companyName}
                  onChange={(e) => setConfig({ ...config, companyName: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  placeholder="Your Company Name"
                />
              </div>
            </div>
          </div>

          {/* Colors */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Brand Colors</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Primary Color
                </label>
                <div className="flex gap-4 items-center">
                  <input
                    type="color"
                    value={config.primaryColor}
                    onChange={(e) => setConfig({ ...config, primaryColor: e.target.value })}
                    className="h-10 w-20 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={config.primaryColor}
                    onChange={(e) => setConfig({ ...config, primaryColor: e.target.value })}
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-lg"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Secondary Color
                </label>
                <div className="flex gap-4 items-center">
                  <input
                    type="color"
                    value={config.secondaryColor}
                    onChange={(e) => setConfig({ ...config, secondaryColor: e.target.value })}
                    className="h-10 w-20 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={config.secondaryColor}
                    onChange={(e) => setConfig({ ...config, secondaryColor: e.target.value })}
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-lg"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Accent Color
                </label>
                <div className="flex gap-4 items-center">
                  <input
                    type="color"
                    value={config.accentColor}
                    onChange={(e) => setConfig({ ...config, accentColor: e.target.value })}
                    className="h-10 w-20 rounded cursor-pointer"
                  />
                  <input
                    type="text"
                    value={config.accentColor}
                    onChange={(e) => setConfig({ ...config, accentColor: e.target.value })}
                    className="flex-1 px-4 py-2 border border-gray-300 rounded-lg"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Report Text */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Report Text</h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Header Text
                </label>
                <input
                  type="text"
                  value={config.headerText}
                  onChange={(e) => setConfig({ ...config, headerText: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg"
                  placeholder="Report title"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Footer Text
                </label>
                <input
                  type="text"
                  value={config.footerText}
                  onChange={(e) => setConfig({ ...config, footerText: e.target.value })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg"
                  placeholder="Footer text"
                />
              </div>

              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="show-branding"
                  checked={config.showTripCostInsightsBranding}
                  onChange={(e) =>
                    setConfig({ ...config, showTripCostInsightsBranding: e.target.checked })
                  }
                  className="h-4 w-4 text-blue-600 rounded"
                />
                <label htmlFor="show-branding" className="ml-2 text-sm text-gray-700">
                  Show "Powered by VoyagrIQ" branding
                </label>
              </div>
            </div>
          </div>

          {/* Color Presets */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-bold mb-4">Color Presets</h2>
            <p className="text-sm text-gray-600 mb-4">
              Choose a preset color theme to quickly style your reports
            </p>
            <div className="grid grid-cols-2 gap-3">
              {Object.entries(COLOR_PRESETS).map(([key, preset]) => (
                <button
                  key={key}
                  onClick={() => handleApplyPreset(key as keyof typeof COLOR_PRESETS)}
                  className="flex items-center gap-3 p-3 border-2 border-gray-200 rounded-lg hover:border-gray-300 hover:bg-gray-50 transition-all cursor-pointer"
                >
                  <div className="flex gap-1">
                    <div
                      className="w-6 h-6 rounded"
                      style={{ backgroundColor: preset.primaryColor }}
                    />
                    <div
                      className="w-6 h-6 rounded"
                      style={{ backgroundColor: preset.secondaryColor }}
                    />
                    <div
                      className="w-6 h-6 rounded"
                      style={{ backgroundColor: preset.accentColor }}
                    />
                  </div>
                  <span className="text-sm font-medium text-gray-700">{preset.name}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4">
            <button
              onClick={handleSave}
              className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors cursor-pointer"
            >
              {saved ? '✓ Saved!' : 'Save Settings'}
            </button>
            <button
              onClick={handleReset}
              className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition-colors cursor-pointer"
            >
              Reset to Default
            </button>
          </div>
        </div>

        {/* Preview Panel */}
        <div className="space-y-6">
          <div className="bg-white rounded-lg shadow-lg p-6 sticky top-8">
            <h2 className="text-xl font-bold mb-4">Preview</h2>
            <div className="border-2 border-gray-200 rounded-lg p-6 space-y-6">
              {/* Header Preview */}
              <div
                className="border-b-2 pb-4"
                style={{ borderColor: config.primaryColor }}
              >
                <div className="flex items-center justify-between">
                  {logoPreview && (
                    <img src={logoPreview} alt="Logo" className="h-12" />
                  )}
                  <div className="flex-1 text-right">
                    <h3
                      className="text-lg font-bold"
                      style={{ color: config.primaryColor }}
                    >
                      {config.companyName}
                    </h3>
                  </div>
                </div>
                <h2
                  className="text-xl font-bold mt-4 text-center"
                  style={{ color: config.secondaryColor }}
                >
                  {config.headerText}
                </h2>
              </div>

              {/* Content Preview */}
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div
                    className="p-4 rounded-lg"
                    style={{ backgroundColor: `${config.primaryColor}20` }}
                  >
                    <div className="text-sm text-gray-600">Total Revenue</div>
                    <div
                      className="text-2xl font-bold"
                      style={{ color: config.primaryColor }}
                    >
                      $15,000
                    </div>
                  </div>
                  <div
                    className="p-4 rounded-lg"
                    style={{ backgroundColor: `${config.secondaryColor}20` }}
                  >
                    <div className="text-sm text-gray-600">Total Trips</div>
                    <div
                      className="text-2xl font-bold"
                      style={{ color: config.secondaryColor }}
                    >
                      8
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-sm">Sample Metric</span>
                    <span
                      className="font-semibold"
                      style={{ color: config.accentColor }}
                    >
                      75%
                    </span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className="h-2 rounded-full"
                      style={{
                        width: '75%',
                        backgroundColor: config.accentColor,
                      }}
                    />
                  </div>
                </div>
              </div>

              {/* Footer Preview */}
              <div className="border-t-2 pt-4 text-center text-sm text-gray-600">
                <p>{config.footerText}</p>
                {config.showTripCostInsightsBranding && (
                  <p className="text-xs mt-1 text-gray-500">
                    Powered by VoyagrIQ
                  </p>
                )}
              </div>
            </div>

            <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
              <p className="text-sm text-blue-800">
                <strong>Note:</strong> These settings will be applied when you generate PDF reports. The preview shows how your reports will look with your custom branding.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
